name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ShaoHui-G
          filename: github-metrics.svg
          base: activity
          config_timezone: Asia/Shanghai
          plugin_calendar: yes
          plugin_calendar_limit: 180
          output_action: commit          # 已有
          committer_token: ${{ secrets.METRICS_TOKEN }}  # ✅ 用你的 classic token 来 push
          committer_branch: main                         # ✅ 明确推到 main
