name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * 0'   # 每周日 UTC 0 点
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ShaoHui-G
          filename: github-metrics.svg
          base: activity
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes              # ↙︎ 开启半年度等距日历
          plugin_isocalendar_duration: half-year
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
