name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'      # 每天 UTC 0 点
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ShaoHui-G
          filename: github-metrics.svg
          base: activity
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes              # ↙︎ 开启半年度等距日历
          plugin_isocalendar_duration: half-year
          output_action: commit
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
